insert all
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Jozefa Pilsudskiego', '95-100' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Dluga', '95-100' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'ks. Piotra Skargi', '95-100' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Konstantynowska', '95-100' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Andrzeja Struga', '95-100' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Aleksandrowska', '95-100' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Konstantego Ildefonsa Galczynskiego', '95-100' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Szczawinska', '95-100' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Astachowice', '95-001' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Badkow', '95-001' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Besiekierz Nawojowy', '95-001' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Biala', '95-001' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Ciosny', '95-001' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Staffa', '95-100' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Glinnik (Palestyna)', '95-002' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Lagiewniki Nowe', '95-002' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Stare Lagiewniki', '95-002' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Jedlicze A', '95-073' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Jastrzebie Gorne', '95-070' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Juliana Tuwima', '95-100' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Parzeczewska', '95-100' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Hoza', '95-100' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Piaskowa', '95-100' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Jagiellonska', '95-100' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Kosynierow', '95-100' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Arkadiusza Musierowicza', '95-100' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Lodzka', '95-100' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Chociszew', '95-045' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Kolonia Bruzyca', '95-070' )
    into ADDRESSES( ADDRESS, POSTAL_CODE ) values( 'Krzemien', '95-073' )
select 1 from dual;

insert all
    into JOB_LIST( JOB_TITLE ) values( 'Dyrektor' )
    into JOB_LIST( JOB_TITLE ) values( 'Menedzer' )
    into JOB_LIST( JOB_TITLE ) values( 'Pediatra' )
    into JOB_LIST( JOB_TITLE ) values( 'Lekarz rodzinny' )
    into JOB_LIST( JOB_TITLE ) values( 'Psycholog' )
    into JOB_LIST( JOB_TITLE ) values( 'Pielegniarz/-arka' )
    into JOB_LIST( JOB_TITLE ) values( 'Ksiegowy/-a' )
    into JOB_LIST( JOB_TITLE ) values( 'Sekretarz/-rka' )
    into JOB_LIST( JOB_TITLE ) values( 'Sprzatacz/-ka' )
    into JOB_LIST( JOB_TITLE ) values( 'Stro¿½' )
select 1 from dual;

insert all
    into MEDICINES( MEDICINE_NAME ) values( 'Loperamid' )
    into MEDICINES( MEDICINE_NAME ) values( 'Ketonal' )
    into MEDICINES( MEDICINE_NAME ) values( 'Xyzal' )
    into MEDICINES( MEDICINE_NAME ) values( 'Cirrus' )
    into MEDICINES( MEDICINE_NAME ) values( 'Groplinosin' )
    into MEDICINES( MEDICINE_NAME ) values( 'Telfast' )
    into MEDICINES( MEDICINE_NAME ) values( 'Avamys' )
    into MEDICINES( MEDICINE_NAME ) values( 'Paracetamol' )
    into MEDICINES( MEDICINE_NAME ) values( 'Acard' )
    into MEDICINES( MEDICINE_NAME ) values( 'Mizodin' )
    into MEDICINES( MEDICINE_NAME ) values( 'Trzy zdrowaœki' )
    into MEDICINES( MEDICINE_NAME ) values( 'Vicodin' )
    into MEDICINES( MEDICINE_NAME ) values( 'Polsen' )
    into MEDICINES( MEDICINE_NAME ) values( 'Polprazol' )
    into MEDICINES( MEDICINE_NAME ) values( 'Polocard' )
    into MEDICINES( MEDICINE_NAME ) values( 'Ospamox' )
    into MEDICINES( MEDICINE_NAME ) values( 'Ospen' )
    into MEDICINES( MEDICINE_NAME ) values( 'Hitaxa' )
    into MEDICINES( MEDICINE_NAME ) values( 'Fluconazole' )
    into MEDICINES( MEDICINE_NAME ) values( 'Controloc Control' )
    into MEDICINES( MEDICINE_NAME ) values( 'Co-Prenessa' )
    into MEDICINES( MEDICINE_NAME ) values( 'Brufen' )
    into MEDICINES( MEDICINE_NAME ) values( 'Asanix' )
    into MEDICINES( MEDICINE_NAME ) values( 'Gutron' )
    into MEDICINES( MEDICINE_NAME ) values( 'Hascovir' )
    into MEDICINES( MEDICINE_NAME ) values( 'Innofer' )
    into MEDICINES( MEDICINE_NAME ) values( 'Metafen' )
    into MEDICINES( MEDICINE_NAME ) values( 'Relpax' )
select 1 from dual;

insert all
    into EMPLOYEES( E_SURNAME, E_NAME, JOB_ID, OFFICE_NUMBER ) values( 'Burzynska', 'Malgorzata', 1, 4 )
    into EMPLOYEES( E_SURNAME, E_NAME, JOB_ID, OFFICE_NUMBER ) values( 'Czajka', 'Fryderyk', 2, 2 )
    into EMPLOYEES( E_SURNAME, E_NAME, JOB_ID, OFFICE_NUMBER ) values( 'Oetker', 'Doktor', 3, 13 )
    into EMPLOYEES( E_SURNAME, E_NAME, JOB_ID, OFFICE_NUMBER ) values( 'Causa', 'Honoris', 4, 11 )
    into EMPLOYEES( E_SURNAME, E_NAME, JOB_ID, OFFICE_NUMBER ) values( 'Quinn', 'Doktor', 4, 10 )
    into EMPLOYEES( E_SURNAME, E_NAME, JOB_ID, OFFICE_NUMBER ) values( 'Prawda', 'Anna', 4, 14 )
    into EMPLOYEES( E_SURNAME, E_NAME, JOB_ID, OFFICE_NUMBER ) values( 'Prawda', 'Przemyslaw', 4, 22 )
    into EMPLOYEES( E_SURNAME, E_NAME, JOB_ID, OFFICE_NUMBER ) values( 'Rzecki', 'Marek', 4, 20 )
    into EMPLOYEES( E_SURNAME, E_NAME, JOB_ID, OFFICE_NUMBER ) values( 'Skiba', 'Barbara', 4, 21 )
    into EMPLOYEES( E_SURNAME, E_NAME, JOB_ID, OFFICE_NUMBER ) values( 'Dom', 'Grzegorz', 5, 12 )
    into EMPLOYEES( E_SURNAME, E_NAME, JOB_ID, OFFICE_NUMBER ) values( 'Oddech', 'Ewelina', 5, 15 )
    into EMPLOYEES( E_SURNAME, E_NAME, JOB_ID, OFFICE_NUMBER ) values( 'Lesny', 'Hubert', 6, 5 )
    into EMPLOYEES( E_SURNAME, E_NAME, JOB_ID, OFFICE_NUMBER ) values( 'Jenot', 'Cecylia', 6, 5 )
    into EMPLOYEES( E_SURNAME, E_NAME, JOB_ID, OFFICE_NUMBER ) values( 'Tulipan', 'Iwona', 6, 6 )
    into EMPLOYEES( E_SURNAME, E_NAME, JOB_ID, OFFICE_NUMBER ) values( 'Sumera', 'Olga', 6, 6 )
    into EMPLOYEES( E_SURNAME, E_NAME, JOB_ID, OFFICE_NUMBER ) values( 'Piernikowski', 'Tomasz', 7, 23 )
    into EMPLOYEES( E_SURNAME, E_NAME, JOB_ID, OFFICE_NUMBER ) values( 'Tym', 'Stanilawa', 8, 2 )
    into EMPLOYEES( E_SURNAME, E_NAME, JOB_ID, OFFICE_NUMBER ) values( 'Rudzki', 'Franciszek', 9, null )
    into EMPLOYEES( E_SURNAME, E_NAME, JOB_ID, OFFICE_NUMBER ) values( 'Kowalska', 'Janina', 9, null )
    into EMPLOYEES( E_SURNAME, E_NAME, JOB_ID, OFFICE_NUMBER ) values( 'Skawinski', 'Piotr', 10, null )
select 1 from dual;

create or replace view MEDICAL_PERSONNEL as
    select EMPLOYEE_ID, E_SURNAME, E_NAME, JOB_ID, OFFICE_NUMBER from EMPLOYEES 
    where JOB_ID >= 3 and JOB_ID <= 5;

insert all
    into SALARIES( EMPLOYEE_ID, SALARY ) values( 1, 25000 )
    into SALARIES( EMPLOYEE_ID, SALARY ) values( 2, 18000 )
    into SALARIES( EMPLOYEE_ID, SALARY ) values( 3, 10000 )
    into SALARIES( EMPLOYEE_ID, SALARY ) values( 4,  8000 )
    into SALARIES( EMPLOYEE_ID, SALARY ) values( 5,  6500 )
    into SALARIES( EMPLOYEE_ID, SALARY ) values( 6,  7200 )
    into SALARIES( EMPLOYEE_ID, SALARY ) values( 7,  7000 )
    into SALARIES( EMPLOYEE_ID, SALARY ) values( 8,  6400 )
    into SALARIES( EMPLOYEE_ID, SALARY ) values( 9,  6800 )
    into SALARIES( EMPLOYEE_ID, SALARY ) values( 10, 6100 )
    into SALARIES( EMPLOYEE_ID, SALARY ) values( 11, 6200 )
    into SALARIES( EMPLOYEE_ID, SALARY ) values( 12, 5000 )
    into SALARIES( EMPLOYEE_ID, SALARY ) values( 13, 5300 )
    into SALARIES( EMPLOYEE_ID, SALARY ) values( 14, 4900 )
    into SALARIES( EMPLOYEE_ID, SALARY ) values( 15, 5000 )
    into SALARIES( EMPLOYEE_ID, SALARY ) values( 16, 7000 )
    into SALARIES( EMPLOYEE_ID, SALARY ) values( 17, 3700 )
    into SALARIES( EMPLOYEE_ID, SALARY ) values( 18, 3200 )
    into SALARIES( EMPLOYEE_ID, SALARY ) values( 19, 3300 )
    into SALARIES( EMPLOYEE_ID, SALARY ) values( 20, 3000 )
select 1 from dual;